### ISSUE TITLE
JWT Authentification: check username

### ISSUE THREAD

**Issue by Mzem** [ralscha/blog#17]
Hello,

I have a question about your JWT Authentification example. 

In the server side, when you recieve a JWT, you extract the username from this token then you check if this username exists in the database.
This means that any valid token will be accepted, no matter who the sender is.
So, a user with a valid token can have access to any secure endpoint, even those which are restricted to some users only.

However, this can be handeled by some client side checking or controller checking. But isn't it better to implement this in the JWTFilter ? And is this considered as a security threat ? 

Thank you

**Comment by ralscha** [comment]
Hi

Yes you are right, in this particular example the application only checks for an existing username and the application does not use authorities.

An important part of the security is the AppUserDetailService. That's the service that reads the user from the database and creates a UserDetail instance:      
https://github.com/ralscha/blog/blob/master/jwt/server/src/main/java/ch/rasc/jwt/security/AppUserDetailService.java#L30-L33

There you see that I set the authorities to an empty collection. But in a real application you have different roles (authorities).     
Spring Security even provides recommended SQL schemas for the user table:           
https://docs.spring.io/spring-security/site/docs/current/reference/html/appendix-schema.html

When you have authorities you can secure your endpoints with the `@PreAuthorize` annotation

Here an example with two different authorities (USER and ADMIN)
```
  @PreAuthorize("hasAuthority('USER')")
  @GetMapping("/public")
  @CrossOrigin
  public String publicService() {
    return "This message is public";
  }

  @PreAuthorize("hasAuthority('ADMIN')")
  @GetMapping("/secret")
  @CrossOrigin
  public String secretService() {
    return "A secret message";
  }
```

Client side security checking is never a good idea. It's just JavaScript and an experienced developer can change the code on the fly in the developer console of the browser. You can hide menus and buttons based on a role a user has, but never hide data this way. Instead you should never load data the user is not permitted to see and always double check permissions on the server when the user sends a request. 

If JWT is a good idea or not is debatable. The problem is that a JWT is like a password and username in one object and you need to store it in a secure place on the client. If a hacker is able to access your JWT he can access the service.

There are articles on the Internet that do not recommend JWT:     
https://scotch.io/bar-talk/why-jwts-suck-as-session-tokens     
http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/     
https://news.ycombinator.com/item?id=13865459     


A few months ago I created another example without JWT, instead it uses the good old session cookie. 
(http only cookies have the advantage that they are not accessible from JavaScript)
  
https://github.com/ralscha/ionic-security-cookie

**Comment by Mzem** [comment]
Thank you for your answer.

I assume that authorities must be handeled, but this doesn't resolve the issue of accessing restricted endpoints with any valid token?

For example, let's say that we have a secure endpoit `/updatePassword` allowed to every user. The client will send his username, the old and the new password and of course his valid token, to update his password.

If the client somehow manages to send a valid username and old password of another user, he will be able to access the endpoit `/updatePassword` with his token and change the password of the other user.

I think that a solution to this is to compare the username extracted from the token to the username sent by the client.

Is there any way to integrate this check in the JWTFilter? Or should it only be done in the `/updatePassword` controller?

**Comment by ralscha** [comment]
Yes. That is what I meant: "Always check permissions on the server."

You don't need to send the username twice. If you send the JWT, old and new password the application only changes the password of the user that's related to this JWT. This way users can't change the password of other users (unless they steal the JWT of the other user)

If somebody knows the username and password of another user he does not need to change it, he can simply login with this information.

**Comment by Mzem** [comment]
Okay I see your point. Thank you for your help.
